categories = [
    "Local Food",
    "Street",
    "Photo spot",
    "Museum",
    "Palace",
    "Temple",
    "Street",
    "Photo spot",
    "Street",
    "Park",
    "Palace",
    "Street",
    "Museum",
    "Photo spot",
    "Street",
    "Park",
    "Park",
    "Street",
    "Convention Center",
    "Park",
]